spring.application.name=recruitment_system
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.security.user.enabled=false

security.token.secret= JOBSJAVA_@123#
security.token.secret.candidate=JOBSJAVA_@123#CANDIDATE

toker.sonar = sqp_058f95874a627351b78544ecd54867eed0d1bae1

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true