spring.application.name=recruitment_system
spring.datasource.url=jdbc:postgresql://localhost:5432/recruitment
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.security.user.enabled=false

security.token.secret= JOBSJAVA_@123#
security.token.secret.candidate=JOBSJAVA_@123#CANDIDATE

toker.sonar = sqp_058f95874a627351b78544ecd54867eed0d1bae1